apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: lfaivre/expiration
          env:
            - name: NAT_URL
              value: 'http://nats-srv:4222'
            - name: NAT_CLUSTER_ID
              value: 'ticketing'
            - name: NAT_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: expiration-redis-srv
